# Generated by Django 6.0.4 on 2026-04-09 18:46

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default=tickets.models.generate_ticket_id, max_length=20, unique=True, verbose_name='ID del Caso')),
                ('remitente_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Cliente')),
                ('remitente_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo del mensaje')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('revision', 'En Revisión'), ('resuelto', 'Resuelto')], default='abierto', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Ticket PQRS',
                'verbose_name_plural': 'Tickets PQRS',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos_pqrs/', verbose_name='Archivo Adjunto')),
                ('subido_por_sistema', models.BooleanField(default=False, verbose_name='¿Descargado del correo?')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
    ]
