# Generated by Django 6.0.4 on 2026-04-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('revision', 'En Revisión'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado / Spam')], default='abierto', max_length=20, verbose_name='Estado'),
        ),
    ]
