# Generated by Django 6.0.4 on 2026-04-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='es_respuesta_agente',
            field=models.BooleanField(default=False, verbose_name='Adjuntado por Unidossis en la Respuesta'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='regional',
            field=models.CharField(blank=True, choices=[('liquidos', 'Regional Líquidos'), ('solidos', 'Regional Sólidos'), ('marly', 'Regional Marly'), ('occidente', 'Regional Occidente'), ('antioquia', 'Regional Antioquia'), ('costa', 'Regional Costa'), ('llanos', 'Regional Llanos')], max_length=50, null=True, verbose_name='Regional Asignada'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='respuesta_oficial',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta de Unidossis'),
        ),
    ]
