# Generated by Django 6.0.4 on 2026-04-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_archivoadjunto_es_respuesta_agente_ticket_regional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='auto_respuesta_enviada',
            field=models.BooleanField(default=False, verbose_name='Acuse de recibo enviado al cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='respuesta_formal_enviada',
            field=models.BooleanField(default=False, verbose_name='Notificación de Cierre enviada al cliente'),
        ),
    ]
