# Generated by Django 6.0.4 on 2026-04-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_auto_respuesta_enviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='linea_servicio',
            field=models.CharField(blank=True, choices=[('administrativo', 'Administrativo'), ('dosis_anticipada', 'Dosis Anticipada'), ('esteriles', 'Esteriles'), ('magistral', 'Magistral No Esteriles'), ('npt', 'NPT'), ('npt_vet', 'NPT Veterinaria'), ('oncologia', 'Oncología'), ('solidos', 'Solidos'), ('todas', 'Todas'), ('logistica_linea', 'Logistica'), ('logistica_blitz', 'Logistica (Blitz)')], max_length=50, null=True, verbose_name='Línea'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='proceso',
            field=models.CharField(blank=True, choices=[('gerencia', 'Gerencia General'), ('produccion', 'Producción y Dirección Técnica'), ('comercial', 'Comercial'), ('logistica', 'Operaciones y Logística'), ('administrativa', 'Administrativa y Financiera'), ('talento', 'Talento Humano'), ('sst', 'Seguridad y Salud en el Trabajo'), ('calidad', 'Aseguramiento de Calidad')], max_length=50, null=True, verbose_name='Área / Proceso'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipificacion',
            field=models.CharField(blank=True, choices=[('producto_no_conforme', 'Producto no conforme'), ('no_conformidad_entrega', 'No conformidad entre lo solicitado y entregado'), ('farmacovigilancia', 'Reporte de farmacovigilancia'), ('diferencia_inventario', 'Diferencia en inventario en custodia'), ('entrega_fuera_acuerdo', 'Entrega fuera del acuerdo de servicio'), ('error_almacenamiento', 'Error almacenamiento/transporte de medicamentos'), ('error_interpretacion', 'Error de interpretación'), ('error_embalaje', 'Error de embalaje'), ('error_empaque', 'Error de empaque'), ('error_re_empaque', 'Error de re empaque'), ('error_etiqueta', 'Error en etiqueta/codificado'), ('error_despacho', 'Error en despacho'), ('incumplimiento', 'Incumplimiento compromisos'), ('resultados_micro', 'Solicitud resultados microbiológicos'), ('solicitud_cliente', 'Solicitud del cliente')], max_length=100, null=True, verbose_name='Tipificación'),
        ),
    ]
