# Generated by Django 6.0.4 on 2026-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_linea_servicio_ticket_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable Asignado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='regional',
            field=models.CharField(blank=True, choices=[('liquidos', 'Regional Líquidos'), ('solidos', 'Regional Sólidos'), ('marly', 'Regional Marly'), ('occidente', 'Regional Occidente'), ('antioquia', 'Regional Antioquia'), ('costa', 'Regional Costa'), ('llanos', 'Regional Llanos'), ('eje_cafetero', 'Eje Cafetero')], max_length=50, null=True, verbose_name='Regional Asignada'),
        ),
    ]
