# Generated by Django 6.0.4 on 2026-04-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_responsable_alter_ticket_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='analisis_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Análisis de IA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='clasificado_por_ia',
            field=models.BooleanField(default=False, verbose_name='Auto-Clasificado por IA'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='regional',
            field=models.CharField(blank=True, choices=[('liquidos', 'Cundinamarca Líquidos'), ('solidos', 'Sólidos'), ('marly', 'Marly'), ('occidente', 'Regional Occidente'), ('antioquia', 'Regional Antioquia'), ('costa', 'Regional Costa'), ('llanos', 'Regional Llanos'), ('eje_cafetero', 'Eje Cafetero')], max_length=50, null=True, verbose_name='Regional Asignada'),
        ),
    ]
