# Generated by Django 6.0.4 on 2026-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_analisis_ia_ticket_clasificado_por_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='criticidad',
            field=models.CharField(blank=True, choices=[('critica', 'Crítica (Riesgo para la vida/salud - Res 0444/1403)'), ('mayor', 'Mayor (Afecta calidad/eficacia - Res 0444/1403)'), ('menor', 'Menor (Defecto estético/documental)'), ('informativa', 'Informativa / Sugerencia')], max_length=20, null=True, verbose_name='Nivel de Criticidad'),
        ),
    ]
