# Generated by Django 6.0.4 on 2026-04-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_criticidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ciudad',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='entidad_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Entidad / Cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='institucion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante_cargo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo del Solicitante'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_solicitud',
            field=models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('pregunta', 'Pregunta'), ('felicitacion', 'Felicitación')], default='queja', max_length=20, verbose_name='Tipo de Solicitud'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remitente_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Solicitante'),
        ),
    ]
