# Generated by Django 6.0.4 on 2026-04-10 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_cargo_ciudad_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.cliente', verbose_name='Perfil del Cliente'),
        ),
    ]
