# Generated by Django 6.0.4 on 2026-04-11 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_cliente_user_ticket_cliente_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ciudad', verbose_name='Ciudad/Municipio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_principal',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Principal (Obligatorio)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='emails_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Correos Adicionales (Separados por coma)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regional',
            field=models.CharField(blank=True, choices=[('liquidos', 'Cundinamarca Líquidos'), ('solidos', 'Sólidos'), ('marly', 'Marly'), ('occidente', 'Regional Occidente'), ('antioquia', 'Regional Antioquia'), ('costa', 'Regional Costa'), ('llanos', 'Regional Llanos'), ('eje_cafetero', 'Eje Cafetero')], max_length=50, null=True, verbose_name='Regional que lo atiende'),
        ),
    ]
