# Generated by Django 6.0.4 on 2026-04-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_cliente_ciudad_cliente_email_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cliente Activo'),
        ),
    ]
