# Generated by Django 6.0.4 on 2026-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_cliente_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestroInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de Referencia')),
            ],
            options={
                'verbose_name': 'Maestro de Institución',
                'verbose_name_plural': 'Maestro de Instituciones',
                'ordering': ['nombre'],
            },
        ),
    ]
