# Generated by Django 6.0.4 on 2026-04-11 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_maestroinstitucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin_pqrs', 'Administrador PQRS'), ('director_regional', 'Director Regional'), ('supervisor', 'Supervisor'), ('cliente', 'Cliente Institución')], default='admin_pqrs', max_length=30)),
                ('regional', models.CharField(blank=True, choices=[('liquidos', 'Cundinamarca Líquidos'), ('solidos', 'Sólidos'), ('marly', 'Marly'), ('occidente', 'Regional Occidente'), ('antioquia', 'Regional Antioquia'), ('costa', 'Regional Costa'), ('llanos', 'Regional Llanos'), ('eje_cafetero', 'Eje Cafetero')], help_text='Solo para Directores Regionales', max_length=50, null=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Solo para usuarios de tipo Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
