# Generated by Django 6.0.4 on 2026-04-14 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración SLA Principal', max_length=100, verbose_name='Nombre de la Configuración')),
                ('dias_alerta_peligro', models.IntegerField(default=11, verbose_name="Días para alerta 'En Peligro'")),
                ('dias_alerta_vencido', models.IntegerField(default=15, verbose_name="Días para alerta 'Vencido / Escalamiento'")),
                ('emails_alerta_peligro', models.TextField(blank=True, default='', help_text='Separados por coma. Ej: regional@unidossis.com, supervisor@unidossis.com', verbose_name="Emails para alertas de 'En Peligro'")),
                ('emails_alerta_vencido', models.TextField(blank=True, default='', help_text='Separados por coma. Ej: admin@unidossis.com, calidad@unidossis.com', verbose_name="Emails para alertas de 'Vencido'")),
                ('celulares_alerta', models.TextField(blank=True, default='', help_text='Solo dígitos, separados por coma. Ej: 3001234567,3109876543', verbose_name='Celulares para alertas (WhatsApp/SMS)')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración activa')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SLA',
                'verbose_name_plural': 'Configuraciones SLA',
            },
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('visibilidad', models.CharField(choices=[('interno', 'Solo equipo interno Unidossis'), ('publico', 'Visible para el cliente')], default='interno', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Comentario de Ticket',
                'verbose_name_plural': 'Comentarios de Tickets',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de respuesta'), ('satisfecho', 'Cliente satisfecho — ticket cerrado'), ('insatisfecho', 'Cliente insatisfecho — ticket reabierto'), ('expirada', 'Encuesta expirada sin respuesta')], default='pendiente', max_length=20)),
                ('puntuacion', models.IntegerField(blank=True, null=True, verbose_name='Puntuación (1-5 estrellas)')),
                ('comentario_cliente', models.TextField(blank=True, null=True, verbose_name='Comentario del cliente')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_csat', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción (CSAT)',
                'verbose_name_plural': 'Encuestas de Satisfacción (CSAT)',
            },
        ),
        migrations.CreateModel(
            name='FeedbackIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_linea_original', models.CharField(blank=True, max_length=50)),
                ('ia_proceso_original', models.CharField(blank=True, max_length=50)),
                ('ia_tipificacion_original', models.CharField(blank=True, max_length=100)),
                ('ia_criticidad_original', models.CharField(blank=True, max_length=20)),
                ('linea_corregida', models.CharField(blank=True, max_length=50)),
                ('proceso_corregido', models.CharField(blank=True, max_length=50)),
                ('tipificacion_corregida', models.CharField(blank=True, max_length=100)),
                ('criticidad_corregida', models.CharField(blank=True, max_length=20)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Razón de la corrección')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('corrector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_ia', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Feedback de IA',
                'verbose_name_plural': 'Feedbacks de IA',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=300, verbose_name='Acción realizada')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle adicional')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AlertaSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peligro', 'Alerta de Peligro (próximo a vencer)'), ('vencido', 'Alerta de Vencimiento / Escalamiento')], max_length=20)),
                ('emails_notificados', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_sla', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Alerta SLA',
                'verbose_name_plural': 'Alertas SLA',
                'unique_together': {('ticket', 'tipo')},
            },
        ),
    ]
