# Generated by Django 6.0.4 on 2026-04-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si está activo, se forzará al usuario a cambiar su contraseña en el próximo login', verbose_name='Debe cambiar contraseña'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('username', models.CharField(max_length=150, verbose_name='Usuario intentado')),
                ('exitoso', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='Navegador')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['ip', 'fecha'], name='tickets_int_ip_28dc66_idx'), models.Index(fields=['username', 'fecha'], name='tickets_int_usernam_66f810_idx')],
            },
        ),
    ]
