# Generated by Django 6.0.4 on 2026-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_perfilusuario_debe_cambiar_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='es_soporte_interno',
            field=models.BooleanField(default=False, verbose_name='Soporte/Evidencia Interna de Gestión'),
        ),
    ]
