# Generated by Django 6.0.4 on 2026-04-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_archivoadjunto_es_soporte_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='regional',
            field=models.CharField(blank=True, choices=[('liquidos', 'Cundinamarca Líquidos'), ('solidos', 'Sólidos'), ('marly', 'Marly'), ('occidente', 'Regional Occidente'), ('antioquia', 'Regional Antioquia'), ('costa', 'Regional Costa'), ('llanos', 'Regional Llanos'), ('eje_cafetero', 'Eje Cafetero')], help_text='Solo para Directores Regionales y Agentes regionales', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin_pqrs', 'Administrador PQRS'), ('director_regional', 'Director Regional'), ('agente', 'Agente / Consultor'), ('cliente', 'Cliente Institución')], default='admin_pqrs', max_length=30),
        ),
    ]
