# Generated by Django 6.0.4 on 2026-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_perfilusuario_regional_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resumen_cliente_ia',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Resumen IA para Cliente'),
        ),
    ]
