# Generated by Django 6.0.4 on 2026-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_add_solicitud_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='notas_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Notas internas del administrador'),
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin_pqrs', 'Administrador PQRS'), ('director_regional', 'Director Regional'), ('agente', 'Agente / Consultor'), ('cliente', 'Cliente Institución')], max_length=30)),
                ('permiso', models.CharField(choices=[('ver_dashboard', 'Ver Dashboard'), ('crear_ticket', 'Crear Ticket Manual'), ('editar_ticket', 'Editar Tickets'), ('eliminar_ticket', 'Eliminar Tickets'), ('responder_ticket', 'Responder Tickets'), ('ver_reportes', 'Ver Reportes'), ('exportar_excel', 'Exportar a Excel'), ('gestionar_clientes', 'Gestionar Clientes'), ('gestionar_usuarios', 'Gestionar Usuarios Internos'), ('configurar_sla', 'Configurar SLA'), ('ver_monitoreo', 'Ver Monitoreo del Sistema'), ('ver_auditoria', 'Ver Logs de Auditoría'), ('acceso_consola', 'Acceder a la Consola Central'), ('ver_analisis_ia', 'Ver Análisis de IA'), ('reclasificar_ia', 'Reclasificar con IA')], max_length=50)),
                ('permitido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permiso por Rol',
                'verbose_name_plural': 'Permisos por Rol',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
