# Generated by Django 6.0.4 on 2026-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_consola_central_permisorol_notas_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código (ej: F-01)')),
                ('name', models.CharField(max_length=50, verbose_name='Identificador técnico')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('version', models.CharField(default='v1.0.0', max_length=20)),
                ('url_name', models.CharField(blank=True, max_length=80, verbose_name='URL name (urls.py)')),
                ('tablas', models.CharField(blank=True, max_length=250, verbose_name='Tablas conectadas (CSV)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción funcional')),
                ('tipo', models.CharField(choices=[('formulario', 'Formulario'), ('vista', 'Vista / Dashboard')], default='formulario', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Componente',
                'verbose_name_plural': 'Registro de Componentes',
                'ordering': ['code'],
            },
        ),
    ]
