# Generated by Django 6.0.4 on 2026-04-21 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_registro_componente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Identificador interno del rol (ej: supervisor_tecnico). Sin espacios.', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Nombre visible del rol (ej: Supervisor Técnico)', max_length=100)),
                ('icono', models.CharField(default='fa-user-tag', help_text='Clase de ícono FontAwesome (ej: fa-user-tie)', max_length=50)),
                ('color_inicio', models.CharField(default='#6b7280', max_length=7)),
                ('color_fin', models.CharField(default='#9ca3af', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol Personalizado',
                'verbose_name_plural': 'Roles Personalizados',
                'ordering': ['label'],
            },
        ),
    ]
